spring.application.name=demo

spring.datasource.username=postgres
spring.datasource.password=02062001
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=employee_info

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081